use_multithreading = false      # 是否启用多线程
allow_over_capacity = false     # 是否允许超过容量选课（用于第一轮选课未踢人情况）
wait_time = 5.0                 # 每次尝试后的等待时间（秒）

browser = "chrome"                # 浏览器类型: "chrome", "firefox", 或 "edge"

# 已选课程本地状态（动态更新）
[selected_courses]
# 示例: {"08305014": "1005"}，课程号和已选教师号

[selected_courses_cache]
updated = false                 # 本地状态是否需要同步
last_sync_time = "2024-12-26T12:00:00"

# 课程信息列表
[[courses]]
KCH = "08305014"    # 课程号
JSH = "1005"        # 教师号
priority = 1        # 优先级，值越低越优先
time_slot = "08:00-10:00"  # 时间段，示例